name: petto_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.13.2
  connectivity_plus: ^5.0.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  go_router: ^12.1.1
  google_nav_bar: ^5.0.6
  icons_plus: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  url_launcher: ^6.2.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
    - assets/icon/
    - assets/animations/
    - data/pettips_es.json
    - data/pettips_en.json
    - data/politics_es.json
    - data/politics_en.json
    - data/terms_en.json
    - data/terms_es.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
