name: petto_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: ^12.1.0
  google_nav_bar: ^5.0.6
  icons_plus: ^4.0.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - data/pettips_es.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
