name: petto_app
description: A new Flutter project.
publish_to: "none"
version: 1.4.0+4

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.5
  connectivity_plus: ^5.0.2
  easy_localization: ^3.0.4
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.18
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  go_router: ^13.2.0
  google_nav_bar: ^5.0.6
  icons_plus: ^5.0.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.3.0
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
    - assets/icon/
    - assets/lang/
    - assets/animations/
    - data/pettips_es.json
    - data/pettips_en.json
    - data/politics_es.json
    - data/politics_en.json
    - data/terms_en.json
    - data/terms_es.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
