import 'package:flutter/material.dart';

const Color lightBackground = Color(0xFFf9f9f9);
const Color lightPrimary = Color(0xFFff6366);
const Color lightPrimaryContainer = Color(0xFFFFDDD7);
const Color lightSurface = Color(0xFFFFFFFF);
const Color lightSurfaceVariant = Color(0xFFFFFFFF);
const Color lightSecondary = Color(0xFF25b1bf);
const Color lightSecondaryContainer = Color(0xFFA3F7FF);
const Color lightTertiary = Color(0xFF3BB725);
const Color lightTertiaryContainer = Color(0xFFC0FFB5);
const Color lightIconColor = Colors.black54;
const Color lightShadowColor = Color.fromRGBO(0, 0, 0, 0.063);
const Color lightTextColor1 = Colors.black;
const Color lightTextColor2 = Colors.black54;
const Color lightTextColor3 = Colors.black38;

const Color darkBackground = Color(0XFF1e293b);
const Color darkPrimary = Color(0xFFff6366);
const Color darkPrimaryContainer = Color(0xFFFFDDD7);
const Color darkSurface = Color(0xFF334155);
const Color darkSurfaceVariant = Color(0xFF334155);
const Color darkSecondary = Color(0xFF25b1bf);
const Color darkSecondaryContainer = Color(0xFFA3F7FF);
const Color darkTertiary = Color(0xFF3BB725);
const Color darkTertiaryContainer = Color(0xFFC0FFB5);
const Color darkIconColor = Colors.white;
const Color darkShadowColor = Color.fromRGBO(0, 0, 0, 0.063);
const Color darkTextColor1 = Colors.white;
const Color darkTextColor2 = Colors.white;
const Color darkTextColor3 = Colors.white;
